import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

const MIGRATIONS_DIR = join(__dirname, "../db-migrations");
const OUTPUT_FILE = join(__dirname, "../db-migrations/reset.sql");

type Mode = "full" | "up" | "down";

interface MigrationFile {
    number: number;
    type: "up" | "down";
    filename: string;
    content: string;
}

function parseArgs(): Mode {
    const arg = process.argv
        .slice(2)
        .find((a) => a === "--up" || a === "--down" || a === "-u" || a === "-d");
    if (arg === "--up" || arg === "-u") return "up";
    if (arg === "--down" || arg === "-d") return "down";
    return "full";
}

function extractMigrationNumber(filename: string): number {
    const match = filename.match(/^(\d+)[a-z]?_/);
    return match ? parseInt(match[1], 10) : -1;
}

function readMigrationFiles(): MigrationFile[] {
    const files = readdirSync(MIGRATIONS_DIR);
    const migrations: MigrationFile[] = [];

    for (const file of files) {
        if (file.endsWith(".up.sql") || file.endsWith(".down.sql")) {
            const number = extractMigrationNumber(file);
            if (number === -1) continue;

            const type = file.endsWith(".up.sql") ? "up" : "down";
            const content = readFileSync(join(MIGRATIONS_DIR, file), "utf-8");

            migrations.push({
                number,
                type,
                filename: file,
                content,
            });
        }
    }

    return migrations;
}

/**
 * Compare migration files by filename (lexicographic).
 * Supports sub-numbered files like 003a_, 003b_ sorting
 * between 003_ and 004_.
 */
function compareMigrations(a: MigrationFile, b: MigrationFile): number {
    return a.filename.localeCompare(b.filename);
}

function generateResetSQL(): void {
    const mode = parseArgs();
    const migrations = readMigrationFiles();

    const downMigrations = migrations
        .filter((m) => m.type === "down")
        .sort((a, b) => compareMigrations(b, a));

    const upMigrations = migrations.filter((m) => m.type === "up").sort(compareMigrations);

    const header = `-- Database Reset Script
-- This file is auto-generated by scripts/generate-reset-sql.ts
-- WARNING: This will drop all tables, types, and functions!
-- Generated at: ${new Date().toISOString()}
-- Mode: ${mode}
--
-- Usage: psql -d your_database -f reset.sql
-- Or execute this file in your database client

BEGIN;

`;

    let sql: string;
    if (mode === "down") {
        sql = header + "-- Rollback all migrations (down)\n\n";
        for (const migration of downMigrations) {
            sql += `-- ${migration.filename}\n`;
            sql += migration.content;
            sql += "\n\n";
        }
        sql += "COMMIT;\n";
    } else if (mode === "up") {
        sql = header + "-- Apply all migrations (up)\n\n";
        for (const migration of upMigrations) {
            sql += `-- ${migration.filename}\n`;
            sql += migration.content;
            sql += "\n\n";
        }
        sql += "COMMIT;\n";
    } else {
        sql = header + "-- STEP 1: Rollback all migrations (down)\n\n";
        for (const migration of downMigrations) {
            sql += `-- ${migration.filename}\n`;
            sql += migration.content;
            sql += "\n\n";
        }
        sql += "-- STEP 2: Apply all migrations (up)\n\n";
        for (const migration of upMigrations) {
            sql += `-- ${migration.filename}\n`;
            sql += migration.content;
            sql += "\n\n";
        }
        sql += "COMMIT;\n";
    }

    writeFileSync(OUTPUT_FILE, sql, "utf-8");
    console.log(`✅ Reset SQL file generated: ${OUTPUT_FILE} (mode: ${mode})`);
    if (mode !== "up") console.log(`   - ${downMigrations.length} down migrations`);
    if (mode !== "down") console.log(`   - ${upMigrations.length} up migrations`);
}

generateResetSQL();
